### Site Settings ###
title               : Cobalt's Website!
description         : Wesbite!
remote_theme        : yousinix/portfolYOU

### Author Info ###
author:
	name								: Cobalt
	youtube							: cicadacobalt
