### Site Settings ###
title               : Cobalt's Website!
description         : Wesbite!
remote_theme        : yousinix/portfolYOU

### Plugins ###
plugins:
  - jemoji

### Author Info ###
author:
  name	            : Cobalt
  youtube           : cicadacobalt
  soundcloud        : cicadacobalt
  github            : cicadacobalt
